# Generated by Django 2.0.3 on 2018-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180326_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='project_list',
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects_administered',
            field=models.ManyToManyField(blank=True, related_name='projects_administered', to='dashboard.Project'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='projects_followed',
            field=models.ManyToManyField(blank=True, related_name='projects_followed', to='dashboard.Project'),
        ),
    ]
