# Generated by Django 2.0.3 on 2018-03-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='dashboard.Project'),
        ),
    ]
