# Generated by Django 2.0.3 on 2018-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180327_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='status',
            field=models.CharField(choices=[('active', ('Active', 'ax')), ('defect', 'Defect Liability Period'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=60, verbose_name='Project Status'),
        ),
    ]
