# Generated by Django 2.0.3 on 2018-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180327_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('defect', 'On DLP'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=60, verbose_name='Project Status'),
        ),
    ]
