# Generated by Django 2.0.3 on 2018-03-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180328_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project contract amount in ETB (before VAT)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.PositiveIntegerField(blank=True, help_text='Project life time in calendar days', null=True, verbose_name='Contract Period'),
        ),
    ]
