# Generated by Django 2.0.3 on 2018-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180328_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatus',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectstatus',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('rectification', 'Rectification'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='unknown', max_length=60, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_claim_admin',
            field=models.BooleanField(default=False, verbose_name='Administer Time Claim Details'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_insurance_admin',
            field=models.BooleanField(default=False, verbose_name='Administer Insurance Details'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_payment_admin',
            field=models.BooleanField(default=False, verbose_name='Administer Payment Details'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_project_admin',
            field=models.BooleanField(default=False, verbose_name='Administer Project Detals'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_variation_admin',
            field=models.BooleanField(default=False, verbose_name='Administer Variation Details'),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
