# Generated by Django 2.0.3 on 2018-03-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180328_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Mobilization'), (3, 'Active'), (4, 'Rectification'), (5, 'Suspended'), (6, 'Terminated'), (7, 'Closed')], default=1, verbose_name='Project Status'),
        ),
    ]
