# Generated by Django 2.0.3 on 2018-03-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180328_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', '-updated_at', 'short_name']},
        ),
    ]
