# Generated by Django 2.0.3 on 2018-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180328_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_types', models.CharField(choices=[('company', 'Company detail configurations'), ('website', 'Website configurations'), ('other', 'Other configurations')], max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Website Configurations',
                'verbose_name': 'Website Configuration',
                'ordering': ['config_types'],
            },
        ),
    ]
