# Generated by Django 2.0.3 on 2018-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180328_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='slug',
            field=models.SlugField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
