# Generated by Django 2.0.3 on 2018-04-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20180407_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', '-updated_at', 'short_name'], 'permissions': (('admin_project', 'Administer Project'),)},
        ),
    ]
