# Generated by Django 2.0.3 on 2018-04-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20180407_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=False, verbose_name='Published status'),
        ),
    ]
