# Generated by Django 2.0.3 on 2018-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20180407_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=True, verbose_name='Published status'),
        ),
    ]
