# Generated by Django 2.0.3 on 2018-04-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20180408_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
    ]
