# Generated by Django 2.0.3 on 2018-04-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_subject',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False, verbose_name='Broadcast to all users'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project'),
        ),
    ]
