# Generated by Django 2.0.3 on 2018-04-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20180413_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_broadcast',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Sent Status'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Seen'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(default='Default Title', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notified_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='seen_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
