# Generated by Django 2.0.3 on 2018-04-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20180414_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('warning', 'Warning')], max_length=100),
        ),
    ]
