# Generated by Django 2.0.3 on 2018-04-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20180415_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion_date',
        ),
    ]
