# Generated by Django 2.0.3 on 2018-04-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20180415_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_title',
            new_name='title',
        ),
    ]
