# Generated by Django 2.0.3 on 2018-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20180416_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
