# Generated by Django 2.0.3 on 2018-04-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_notification_is_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='Send notification to all users'),
        ),
    ]
