# Generated by Django 2.0.3 on 2018-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20180417_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='activities',
            field=models.ManyToManyField(related_name='activity_plans', to='dashboard.Activity', verbose_name='Planned Activities'),
        ),
        migrations.AlterField(
            model_name='report',
            name='activities',
            field=models.ManyToManyField(related_name='activity_reports', to='dashboard.Activity', verbose_name='Executed Activities'),
        ),
    ]
