# Generated by Django 2.0.3 on 2018-04-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20180421_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated date and time')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Executed Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of executed works')),
                ('slippage_reason', models.TextField(blank=True, null=True, verbose_name='Reasons and descrioption of slippage')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Additional Notes and Remarks')),
                ('activities', models.ManyToManyField(related_name='activity_reports', to='dashboard.Activity', verbose_name='Executed Activities')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_list', to='dashboard.Plan')),
            ],
            options={
                'permissions': (('admin_progress', 'Administer Progress'),),
                'ordering': ['plan', '-updated_at'],
                'get_latest_by': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='report',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
