# Generated by Django 2.0.3 on 2018-04-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20180423_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='notify_to',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'get_latest_by': ['-updated_at'], 'ordering': ['-is_seen', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_broadcast',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Sent Status'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Seen'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='seen_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='projects_administered',
            field=models.ManyToManyField(blank=True, related_name='admins', to='dashboard.Project'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='projects_followed',
            field=models.ManyToManyField(blank=True, related_name='followers', to='dashboard.Project'),
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
