# Generated by Django 2.0.3 on 2018-04-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_auto_20180424_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_notifications', to='dashboard.Project'),
        ),
    ]
