# Generated by Django 2.0.3 on 2018-04-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_auto_20180426_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='project',
        ),
    ]
