# Generated by Django 2.0.3 on 2018-04-27 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='commencement_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='commencement Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Project contract amount in ETB (before VAT)', max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.PositiveIntegerField(default=100, help_text='Project life time in calendar days', verbose_name='Contract Period'),
            preserve_default=False,
        ),
    ]
