# Generated by Django 2.0.3 on 2018-04-28 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20180427_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Schedule End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Schedule Start Date'),
            preserve_default=False,
        ),
    ]
