# Generated by Django 2.0.3 on 2018-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20180428_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'get_latest_by': ['-updated_at'], 'ordering': ['schedule', 'week'], 'permissions': (('admin_plan', 'Administer Plans'),), 'verbose_name': 'Schedule Plan', 'verbose_name_plural': 'Schedule Plans'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='week',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Week Number'),
            preserve_default=False,
        ),
    ]
