# Generated by Django 2.0.3 on 2018-04-29 11:13

import dashboard.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20180429_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET(dashboard.utils.get_phantom_user), related_name='projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
