# Generated by Django 2.0.3 on 2018-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20180429_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='week',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Week Number'),
        ),
    ]
