# Generated by Django 2.0.3 on 2018-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20180429_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date and time', verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date and time', verbose_name='Last updated'),
        ),
    ]
