# Generated by Django 2.0.3 on 2018-04-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_auto_20180430_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'get_latest_by': ['-updated_at'], 'ordering': ['project', 'week', '-updated_at'], 'permissions': (('admin_progress', 'Administer Progress'),)},
        ),
        migrations.AddField(
            model_name='progress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='week',
            field=models.PositiveIntegerField(default=1, verbose_name='Week no'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='progress',
            name='plan',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('project', 'week')},
        ),
    ]
